<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Program</name>
   <tag></tag>
   <elementGuidId>22afe769-f3a7-492f-ad76-69e1691b2ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[5]/div/header/div/div/nav/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65442998-1d5d-4a3c-b17e-b952f9513e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-0-0-26 sans-0-0-40 heading-4-0-0-48 clickable-0-0-28 nav-0-0-748</value>
      <webElementGuid>de33edb7-3d60-4cf6-beb4-0c1a9939edc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/program</value>
      <webElementGuid>87c4795a-19bb-4219-8842-115413e4e968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Program</value>
      <webElementGuid>b7b981cd-027f-4f0c-bee2-dececb303257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;box-0-0-1 flex-0-0-2 container-0-0-176 page-0-0-229&quot;]/div[@class=&quot;box-0-0-1 content-0-0-178 content-0-0-232&quot;]/header[@class=&quot;box-0-0-1 centerX-0-0-5 container-0-0-741&quot;]/div[@class=&quot;box-0-0-1 flex-0-0-2 centerY-0-0-6&quot;]/div[@class=&quot;box-0-0-1 flex-0-0-2 row-0-0-4&quot;]/nav[@class=&quot;box-0-0-1 flex-0-0-2 row-0-0-4 centerY-0-0-6 navigation-0-0-747&quot;]/a[@class=&quot;text-0-0-26 sans-0-0-40 heading-4-0-0-48 clickable-0-0-28 nav-0-0-748&quot;]</value>
      <webElementGuid>59e46cd8-88b0-47ba-895a-b31fa93dfa2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[5]/div/header/div/div/nav/a[2]</value>
      <webElementGuid>c346b114-3105-4b75-85b6-d239a160218c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Program')]</value>
      <webElementGuid>acb7fde5-96c5-435a-b136-276e2e5ed9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::a[1]</value>
      <webElementGuid>07b5db6a-6dc5-4618-bb5f-28df1de9a9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telepon: 021 57946104'])[1]/preceding::a[1]</value>
      <webElementGuid>5d1c3426-6b5b-4019-b993-7adbd9c27b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[2]/preceding::a[2]</value>
      <webElementGuid>75c609c6-1cd7-408d-963a-df177134fb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Program']/parent::*</value>
      <webElementGuid>0109ad16-51bf-4cba-8d55-c6f88e684568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/program')]</value>
      <webElementGuid>d080ffc7-2726-4094-bc3a-73d3ce01311f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>79167b08-322a-494a-8d5a-bdb20b145e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/program' and (text() = 'Program' or . = 'Program')]</value>
      <webElementGuid>f4a3aefc-9ce3-4f82-a98b-d5023534a40d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
