<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Daftar_input-0-0-79 input-valid-0-0-9_92e54d</name>
   <tag></tag>
   <elementGuidId>c0b04171-63ef-4d44-af85-c53bdde45870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='r']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-0-0-79.input-valid-0-0-90.input-focused-0-0-87.inputBox-0-0-253</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb69fef8-8053-41bc-bbd6-7213c8a51574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alamat email yang terdaftar</value>
      <webElementGuid>8178c271-403d-42c6-82c1-186a4b1fa8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d8a10865-fb7e-4f23-a421-6500b0e86f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4813bbd6-f5fd-435c-add4-66451d9d49b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e6302d9-632f-4fa2-95f2-f1058cb0932a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b699fcd3-0ee7-4bad-9f8e-c7853b4193bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-0-0-79 input-valid-0-0-90 input-focused-0-0-87 inputBox-0-0-253</value>
      <webElementGuid>646b0112-cac6-42f2-b053-4d82facc065c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>163a6497-85f7-436f-b46a-0cbe7b5fe668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;box-0-0-1 unaccessibleSelf-0-0-12 container-0-0-385&quot;]/div[@class=&quot;box-0-0-1 centering-0-0-7 transitioner-0-0-386&quot;]/div[@class=&quot;box-0-0-1 container-0-0-902 modal-0-0-752&quot;]/div[@class=&quot;box-0-0-1 formLogin-0-0-907&quot;]/div[@class=&quot;box-0-0-1&quot;]/div[@class=&quot;box-0-0-1 row-0-0-4 centering-0-0-7 clickable-0-0-8 container-0-0-78 container-valid-0-0-85 container-focused-0-0-82 input-0-0-250&quot;]/input[@class=&quot;input-0-0-79 input-valid-0-0-90 input-focused-0-0-87 inputBox-0-0-253&quot;]</value>
      <webElementGuid>c49556fa-082d-4234-85ed-04239faa7c1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='r']</value>
      <webElementGuid>09b8eae3-9d12-40f6-a520-97a9c69df15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div[2]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>08eb1ae3-697d-4429-b6b3-0d225396ca3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>72e1edf6-55d5-4b22-b660-cb5acc8366c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan alamat email yang terdaftar' and @type = 'email']</value>
      <webElementGuid>0f78ce2c-ebe8-4e5f-8ae7-509a38af97aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
