<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Daftar_input-0-0-79 input-valid-0-0-9_92e54d_1</name>
   <tag></tag>
   <elementGuidId>c087a003-491b-4e48-889f-c0f2e297bf3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='@']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-0-0-79.input-valid-0-0-90.input-focused-0-0-87.inputBox-0-0-253</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9edc7d22-9e24-4185-85a5-164eadea97a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kata Sandi</value>
      <webElementGuid>2db43a6d-da73-47d8-a116-08a0fe28d889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>58da196f-1da4-4a44-aec1-36c913f85d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7d77f731-c89a-4e80-923e-4637d6277e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d8ffe816-09bc-401d-9250-1e93c6c9f748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5d35abfb-c23a-47f5-aee8-1c25e008ce90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-0-0-79 input-valid-0-0-90 input-focused-0-0-87 inputBox-0-0-253</value>
      <webElementGuid>379d6c17-5f77-4362-9bcf-ffa4190c0e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>@</value>
      <webElementGuid>1bf2cfd6-bd52-43a4-886f-307383e7d5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;box-0-0-1 unaccessibleSelf-0-0-12 container-0-0-385&quot;]/div[@class=&quot;box-0-0-1 centering-0-0-7 transitioner-0-0-386&quot;]/div[@class=&quot;box-0-0-1 container-0-0-902 modal-0-0-752&quot;]/div[@class=&quot;box-0-0-1 formLogin-0-0-907&quot;]/div[@class=&quot;box-0-0-1 input-0-0-910&quot;]/div[@class=&quot;box-0-0-1 row-0-0-4 centering-0-0-7 clickable-0-0-8 container-0-0-78 container-valid-0-0-85 container-focused-0-0-82 input-0-0-250&quot;]/input[@class=&quot;input-0-0-79 input-valid-0-0-90 input-focused-0-0-87 inputBox-0-0-253&quot;]</value>
      <webElementGuid>61f426e4-c778-4ac7-9e28-ca76c0ab828a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='@']</value>
      <webElementGuid>381e9bad-0a49-4f74-93d3-9b05466ab368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div[2]/div/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>9961825c-5bac-4848-98d6-b2f18eb5549b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>66c8770a-d55d-4b7c-91a6-77c66d196381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Kata Sandi' and @type = 'password']</value>
      <webElementGuid>82b10cbb-9aa9-4e70-81b0-58d20c178b88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
