<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>a416bedb-fbac-4425-aa4d-596243df20ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'email']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='r']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-0-0-79.input-valid-0-0-90.input-focused-0-0-87.inputBox-0-0-253</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e9163d6-1674-452d-9fcb-fb8c6d5a596e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alamat email yang terdaftar</value>
      <webElementGuid>dbcb5485-ab3e-4b5c-98a5-bca15db33d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5dde8fff-4aa8-4dc6-993f-6e30a4742fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>68715781-4676-4a00-95e6-89dea02e3a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e6aa952-bd13-44e3-beda-7f29941f77a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>6734bb0c-7a71-48f6-8bd3-f64cbaa39cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-0-0-79 input-valid-0-0-90 input-focused-0-0-87 inputBox-0-0-253</value>
      <webElementGuid>521d711b-a26e-4a09-be86-d5509889a48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>14540f96-ff32-4cdf-b32e-655ba857fd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;box-0-0-1 unaccessibleSelf-0-0-12 container-0-0-374&quot;]/div[@class=&quot;box-0-0-1 centering-0-0-7 transitioner-0-0-375&quot;]/div[@class=&quot;box-0-0-1 container-0-0-854 modal-0-0-737&quot;]/div[@class=&quot;box-0-0-1 formLogin-0-0-859&quot;]/div[@class=&quot;box-0-0-1&quot;]/div[@class=&quot;box-0-0-1 row-0-0-4 centering-0-0-7 clickable-0-0-8 container-0-0-78 container-valid-0-0-85 container-focused-0-0-82 input-0-0-250&quot;]/input[@class=&quot;input-0-0-79 input-valid-0-0-90 input-focused-0-0-87 inputBox-0-0-253&quot;]</value>
      <webElementGuid>ea3d6bf8-5d66-4d69-872b-d7eb2ddbdfd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>box-0-0-1 row-0-0-4 centering-0-0-7 clickable-0-0-8 container-0-0-78 container-valid-0-0-85 input-0-0-250</value>
      <webElementGuid>342a4a45-0d44-42dc-a450-6fa23257662f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
