<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>9ed4589c-e652-4d4a-ac34-62db4d0a1c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'password']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='J']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-0-0-79.input-valid-0-0-90.input-focused-0-0-87.inputBox-0-0-253</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b091d68-b188-4a3a-864e-723124c7da2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kata Sandi</value>
      <webElementGuid>5302203e-ffcd-463a-9f11-9191c2995cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c20f25e6-954b-47aa-82dd-370aeb4ea074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ef479a70-4c49-4add-8271-89cf92a98978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eab02ea9-e973-48bc-bfe0-7e894a19fb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>09a9e7f6-7682-49fa-b418-fec426286028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-0-0-79 input-valid-0-0-90 input-focused-0-0-87 inputBox-0-0-253</value>
      <webElementGuid>8871b7ce-859f-4695-9602-b4bfc069ff93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>J</value>
      <webElementGuid>d0071643-33c2-4c7e-83ba-b5555aa1793b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;box-0-0-1 unaccessibleSelf-0-0-12 container-0-0-374&quot;]/div[@class=&quot;box-0-0-1 centering-0-0-7 transitioner-0-0-375&quot;]/div[@class=&quot;box-0-0-1 container-0-0-854 modal-0-0-737&quot;]/div[@class=&quot;box-0-0-1 formLogin-0-0-859&quot;]/div[@class=&quot;box-0-0-1 input-0-0-862&quot;]/div[@class=&quot;box-0-0-1 row-0-0-4 centering-0-0-7 clickable-0-0-8 container-0-0-78 container-valid-0-0-85 container-focused-0-0-82 input-0-0-250&quot;]/input[@class=&quot;input-0-0-79 input-valid-0-0-90 input-focused-0-0-87 inputBox-0-0-253&quot;]</value>
      <webElementGuid>c76fb47a-94cb-49dd-8ebe-bcd39498fdd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='J']</value>
      <webElementGuid>15b0a7f9-ff2c-4130-8573-b3f5dbcc9af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>input-0-0-79 input-valid-0-0-90 inputBox-0-0-253</value>
      <webElementGuid>b95c05fb-6790-450d-bb0f-c995053f3f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>bef1cc4e-1199-48d2-adaf-c1b7e8ea5810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Kata Sandi' and @type = 'password']</value>
      <webElementGuid>ad915c2b-267b-4074-b50f-06b5a10eb510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
