<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Keluar</name>
   <tag></tag>
   <elementGuidId>f7f10da2-c503-49c4-b102-2458ecc57b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[5]/header/div/div/nav/div[2]/div/div[2]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.box-0-0-1.row-0-0-4.centerY-0-0-6.clickable-0-0-8.link-0-0-213.transition-0-0-76.hover-0-0-216.big-0-0-217.bigHover-0-0-218</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db362950-6c33-4290-813f-9888ac9c0bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>menu-logout</value>
      <webElementGuid>77b85dea-e000-43db-8464-fd180a9fd126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-0-0-1 row-0-0-4 centerY-0-0-6 clickable-0-0-8 link-0-0-213 transition-0-0-76 hover-0-0-216 big-0-0-217 bigHover-0-0-218</value>
      <webElementGuid>3d11b76e-f007-4f20-95a3-6ded1d49057a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>658c5b41-261d-4845-8ce6-a5bb97f01dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;box-0-0-1 flex-0-0-2&quot;]/header[@class=&quot;box-0-0-1 centerX-0-0-5 container-0-0-741&quot;]/div[@class=&quot;box-0-0-1 flex-0-0-2 centerY-0-0-6&quot;]/div[@class=&quot;box-0-0-1 flex-0-0-2 row-0-0-4&quot;]/nav[@class=&quot;box-0-0-1 flex-0-0-2 row-0-0-4 centerY-0-0-6 navigation-0-0-747&quot;]/div[@class=&quot;box-0-0-1 row-0-0-4 container-0-0-219&quot;]/div[@class=&quot;box-0-0-1 clickable-0-0-8 clicker-0-0-223&quot;]/div[@class=&quot;box-0-0-1 shadow-0-0-1380 navigation-0-0-220 big-0-0-221 top-0-0-225 right-0-0-228 content-0-0-736&quot;]/div[@class=&quot;box-0-0-1 row-0-0-4 centerY-0-0-6 clickable-0-0-8 link-0-0-213 transition-0-0-76 hover-0-0-216 big-0-0-217 bigHover-0-0-218&quot;]</value>
      <webElementGuid>90f147ce-6978-426f-b71c-4a7b44119b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[5]/header/div/div/nav/div[2]/div/div[2]/div[4]</value>
      <webElementGuid>76645b3c-e00b-4b4d-bca4-4ae1c179af85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifikasi'])[1]/following::div[12]</value>
      <webElementGuid>4005acf4-05a5-4420-8742-d9e20e135e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[1]/following::div[13]</value>
      <webElementGuid>ddd34cee-3820-4231-9282-588ce4d3f570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bersertifikat'])[1]/preceding::div[13]</value>
      <webElementGuid>fb32286c-df1d-426a-9904-ce6450ff363f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='di sini'])[1]/preceding::div[65]</value>
      <webElementGuid>0a3eddf0-3627-4a25-a07d-edbed2465430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]</value>
      <webElementGuid>b7a40360-4d7e-4af5-9504-f0922e6fd5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>49743f99-d793-4176-be45-41a1107e5277</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
