<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AkunKegiatankuSurvei KebhinekaanKeluar</name>
   <tag></tag>
   <elementGuidId>1032e018-32b5-4897-aa17-043c89a83919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[5]/header/div/div/nav/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.box-0-0-1.clickable-0-0-8.clicker-0-0-223</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7cd6f99e-4185-4472-8189-2b66c76baf7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>dropdown-menu-account</value>
      <webElementGuid>e8b3b43b-2739-42f5-93e9-c4f68fd13f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3328ced2-6a54-4eca-bd37-fe6d4a373bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-0-0-1 clickable-0-0-8 clicker-0-0-223</value>
      <webElementGuid>efd8267a-88cd-424f-99d4-2bc0164ea897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AkunKegiatankuSurvei KebhinekaanKeluar</value>
      <webElementGuid>6eab0fa3-1370-47be-adf2-14f99201d572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;box-0-0-1 flex-0-0-2&quot;]/header[@class=&quot;box-0-0-1 centerX-0-0-5 container-0-0-741&quot;]/div[@class=&quot;box-0-0-1 flex-0-0-2 centerY-0-0-6&quot;]/div[@class=&quot;box-0-0-1 flex-0-0-2 row-0-0-4&quot;]/nav[@class=&quot;box-0-0-1 flex-0-0-2 row-0-0-4 centerY-0-0-6 navigation-0-0-747&quot;]/div[@class=&quot;box-0-0-1 row-0-0-4 container-0-0-219&quot;]/div[@class=&quot;box-0-0-1 clickable-0-0-8 clicker-0-0-223&quot;]</value>
      <webElementGuid>55c7bb64-3189-4a4d-9982-18bb556f5fdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[5]/header/div/div/nav/div[2]/div</value>
      <webElementGuid>3a705e6d-8e6e-4557-a418-6c039fdc24ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifikasi'])[1]/following::div[2]</value>
      <webElementGuid>6bccfe77-e6f0-4faa-b475-7234fa259f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[1]/following::div[3]</value>
      <webElementGuid>9221dc9d-ca74-4c61-a55f-7e1ff8d3d159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bersertifikat'])[1]/preceding::div[23]</value>
      <webElementGuid>8fee7f5d-52aa-4154-b4d9-618a89b31c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='di sini'])[1]/preceding::div[75]</value>
      <webElementGuid>0bb47dc1-a313-40bc-be95-a705c62ed2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[2]/div</value>
      <webElementGuid>87cdfdf5-93ef-4d11-8795-e784cda520d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AkunKegiatankuSurvei KebhinekaanKeluar' or . = 'AkunKegiatankuSurvei KebhinekaanKeluar')]</value>
      <webElementGuid>416c039e-583b-45c1-b3f9-cfaa31f0af5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
