<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beranda</name>
   <tag></tag>
   <elementGuidId>aca2161f-8d0a-4ae1-b40e-ca49bcb0fd90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[5]/div/header/div/div/nav/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.text-0-0-26.sans-0-0-40.heading-4-0-0-48.clickable-0-0-28.nav-0-0-748</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7236612-38a6-4cdf-8c6a-14540cd7e431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-0-0-26 sans-0-0-40 heading-4-0-0-48 clickable-0-0-28 nav-0-0-748</value>
      <webElementGuid>b58fc2e6-fd6a-419f-b86a-dd7fe51d8b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>2653d712-e818-4c93-9b3e-549dba1ae095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beranda</value>
      <webElementGuid>f84890cf-326f-476b-8a9a-e56c6a2525a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;box-0-0-1 flex-0-0-2 container-0-0-176 page-0-0-229&quot;]/div[@class=&quot;box-0-0-1 content-0-0-178 content-0-0-232&quot;]/header[@class=&quot;box-0-0-1 centerX-0-0-5 container-0-0-741&quot;]/div[@class=&quot;box-0-0-1 flex-0-0-2 centerY-0-0-6&quot;]/div[@class=&quot;box-0-0-1 flex-0-0-2 row-0-0-4&quot;]/nav[@class=&quot;box-0-0-1 flex-0-0-2 row-0-0-4 centerY-0-0-6 navigation-0-0-747&quot;]/a[@class=&quot;text-0-0-26 sans-0-0-40 heading-4-0-0-48 clickable-0-0-28 nav-0-0-748&quot;]</value>
      <webElementGuid>c809de7e-a015-4247-b8a8-a3137369c31f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[5]/div/header/div/div/nav/a</value>
      <webElementGuid>7fb6b669-682b-4331-b87d-aa333b2bed70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Beranda')]</value>
      <webElementGuid>1a3ed2a2-245a-4cc4-9067-98d51dca9e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[1]/preceding::a[1]</value>
      <webElementGuid>dfe8d15b-1b8e-4629-9d6b-56b39294ad1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum berada di semester 4 (empat) pada tahun akademik 2021/2022'])[1]/preceding::a[2]</value>
      <webElementGuid>fa42f6a3-aae6-4471-a8e4-256f1a288ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beranda']/parent::*</value>
      <webElementGuid>a22c7225-d9b4-46bb-aed4-3d84f688f0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/')]</value>
      <webElementGuid>5a789671-5b33-406e-969b-e6ae96a8f48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>d5fc8caf-02e3-4554-8439-465f2cc7c0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'Beranda' or . = 'Beranda')]</value>
      <webElementGuid>07d0d960-7df2-4b7a-b7b3-96a2eef7aeb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
